import { createRequestTypes } from '../../../store/utils';

const FETCH_PROJECTS = 'FETCH_PROJECTS';
const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
const FETCH_PROJECT_BY_ID = 'FETCH_PROJECT_BY_ID';
const FETCH_PROJECT_BY_ID_REQUEST = 'FETCH_PROJECT_BY_ID_REQUEST';
const FETCH_PROJECT_BY_ID_SUCCESS = 'FETCH_PROJECT_BY_ID_SUCCESS';
const FETCH_PROJECT_BY_ID_FAILURE = 'FETCH_PROJECT_BY_ID_FAILURE';
const SELECT_PROJECT = 'SELECT_PROJECT';
const SELECT_PROJECT_SUCCESS = 'SELECT_PROJECT_SUCCESS';
const SELECT_PROJECT_FAILURE = 'SELECT_PROJECT_FAILURE';
const UPDATE_PROJECT = createRequestTypes('UPDATE_PROJECT');
const CREATE_PROJECT = createRequestTypes('CREATE_PROJECT');
const REMOVE_PROJECT = createRequestTypes('REMOVE_PROJECT');

export default {
  FETCH_PROJECTS,
  FETCH_PROJECTS_REQUEST,
  FETCH_PROJECTS_SUCCESS,
  FETCH_PROJECTS_FAILURE,
  FETCH_PROJECT_BY_ID,
  FETCH_PROJECT_BY_ID_REQUEST,
  FETCH_PROJECT_BY_ID_SUCCESS,
  FETCH_PROJECT_BY_ID_FAILURE,
  SELECT_PROJECT,
  SELECT_PROJECT_SUCCESS,
  SELECT_PROJECT_FAILURE,
  UPDATE_PROJECT,
  CREATE_PROJECT,
  REMOVE_PROJECT,
};
