import { createRequestTypes } from '../../../store/utils';

const FETCH_QUESTION_ARTICLES = createRequestTypes('FETCH_QUESTION_ARTICLES');
const UPDATE_QUESTION_ARTICLE = createRequestTypes('UPDATE_QUESTION_ARTICLE');
const CREATE_QUESTION_ARTICLE = createRequestTypes('CREATE_QUESTION_ARTICLE');
const REMOVE_QUESTION_ARTICLE = createRequestTypes('REMOVE_QUESTION_ARTICLE');
const SELECT_QUESTION_ARTICLE = createRequestTypes('SELECT_QUESTION_ARTICLE');
const SEARCH_QUESTION_ARTICLES = createRequestTypes('SEARCH_QUESTION_ARTICLES');
const SEARCH_QUESTION_ARTICLES_CLEAR = 'SEARCH_QUESTION_ARTICLES_CLEAR';
const GIVE_FEEDBACK_ARTICLE = createRequestTypes('GIVE_FEEDBACK_ARTICLE');
const FETCH_QUESTION_ARTICLE_BY_ID = createRequestTypes(
  'FETCH_QUESTION_ARTICLE_BY_ID'
);
const FETCH_QUESTION_CATEGORIES = createRequestTypes(
  'FETCH_QUESTION_CATEGORIES'
);
const FETCH_QUESTION_CATEGORIES_IF_NEEDED =
  'FETCH_QUESTION_CATEGORIES_IF_NEEDED';
const UPDATE_QUESTION_CATEGORY = createRequestTypes('UPDATE_QUESTION_CATEGORY');
const CREATE_QUESTION_CATEGORY = createRequestTypes('CREATE_QUESTION_CATEGORY');
const REMOVE_QUESTION_CATEGORY = createRequestTypes('REMOVE_QUESTION_CATEGORY');
const SELECT_QUESTION_CATEGORY = createRequestTypes('SELECT_QUESTION_CATEGORY');
const FETCH_QUESTION_CATEGORY_BY_ID = createRequestTypes(
  'FETCH_QUESTION_CATEGORY_BY_ID'
);

export default {
  UPDATE_QUESTION_ARTICLE,
  FETCH_QUESTION_ARTICLES,
  GIVE_FEEDBACK_ARTICLE,
  FETCH_QUESTION_ARTICLE_BY_ID,
  CREATE_QUESTION_ARTICLE,
  REMOVE_QUESTION_ARTICLE,
  SELECT_QUESTION_ARTICLE,
  SEARCH_QUESTION_ARTICLES,
  SEARCH_QUESTION_ARTICLES_CLEAR,
  FETCH_QUESTION_CATEGORIES,
  FETCH_QUESTION_CATEGORIES_IF_NEEDED,
  UPDATE_QUESTION_CATEGORY,
  CREATE_QUESTION_CATEGORY,
  REMOVE_QUESTION_CATEGORY,
  FETCH_QUESTION_CATEGORY_BY_ID,
  SELECT_QUESTION_CATEGORY,
};
