const FETCH_EXPENSES = 'FETCH_EXPENSES';
const FETCH_EXPENSES_REQUEST = 'FETCH_EXPENSES_REQUEST';
const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
const FETCH_EXPENSES_FAILURE = 'FETCH_EXPENSES_FAILURE';
const FETCH_EXPENSE_BY_ID = 'FETCH_EXPENSE_BY_ID';
const FETCH_EXPENSE_BY_ID_REQUEST = 'FETCH_EXPENSE_BY_ID_REQUEST';
const FETCH_EXPENSE_BY_ID_SUCCESS = 'FETCH_EXPENSE_BY_ID_SUCCESS';
const FETCH_EXPENSE_BY_ID_FAILURE = 'FETCH_EXPENSE_BY_ID_FAILURE';
const SELECT_EXPENSE = 'SELECT_EXPENSE';
const SELECT_EXPENSE_SUCCESS = 'SELECT_EXPENSE_SUCCESS';
const SELECT_EXPENSE_FAILURE = 'SELECT_EXPENSE_FAILURE';

export default {
  FETCH_EXPENSES,
  FETCH_EXPENSES_REQUEST,
  FETCH_EXPENSES_SUCCESS,
  FETCH_EXPENSES_FAILURE,
  FETCH_EXPENSE_BY_ID,
  FETCH_EXPENSE_BY_ID_REQUEST,
  FETCH_EXPENSE_BY_ID_SUCCESS,
  FETCH_EXPENSE_BY_ID_FAILURE,
  SELECT_EXPENSE,
  SELECT_EXPENSE_SUCCESS,
  SELECT_EXPENSE_FAILURE,
};
